bloggingapp/urls.py
from django.conf.urls.static import static
from django.urls import path
from django.contrib import admin  # Import admin from django.contrib
from bloggingapp import settings
from gallery import views
from gallery.views import post_list

urlpatterns = [
                  path('', views.post_list, name='post_list'),
                  path('signin/', views.signin, name="signin"),
                  path('signout', views.signout, name="signout"),
                  path('post/<int:pk>/', views.post_detail, name='post_detail'),
                  path('search', views.search, name="search"),
                  path('posts/<str:category>/', post_list, name='post_list_filtered'),
                  path('post/new/', views.post_new, name='post_new'),
                  path('post/<int:pk>/edit/', views.post_edit, name='post_edit'),
                  path('post/<int:pk>/delete/', views.post_delete, name='post_delete'),
                  path('admin/', admin.site.urls),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gallery/models.py
# models.py
from django.contrib.auth.models import User
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)
    image = models.ImageField(upload_to='post_images/', blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)  # Allow NULL for author
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

gallery/views.py
# views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.db.models import Q
from django.forms import forms
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.utils import timezone

import gallery.views
from .app_form import PostForm, LoginForm
from .models import Post, Category
from django.shortcuts import redirect


@login_required
@permission_required('gallery.view_post', raise_exception=True)
def post_list(request, category=None):
    if category:
        # Use get_object_or_404 to handle the case where the category doesn't exist
        selected_category = get_object_or_404(Category, name=category)
        posts = Post.objects.filter(category=selected_category)
    else:
        posts = Post.objects.all()
        selected_category = None  # No specific category selected

    categories = Category.objects.all()  # Fetch all categories
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    data = paginator.get_page(page_number)

    return render(request, 'post_list.html', {'posts': data, 'categories': categories, 'selected_category': selected_category})


@login_required
@permission_required('gallery.view_post', raise_exception=True)
def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'post_detail.html', {'post': post})


@login_required
@permission_required('gallery.add_post', raise_exception=True)
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user  # Set the author to the logged-in user
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        categories = Category.objects.all()
        form = PostForm()
    return render(request, 'post_edit.html', {'form': form, 'categories': categories})


@login_required
@permission_required('gallery.change_post', raise_exception=True)
def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        categories = Category.objects.all()
        form = PostForm(instance=post)
    return render(request, 'post_edit.html', {'form': form, 'categories': categories})


@login_required
@permission_required('gallery.delete_post', raise_exception=True)
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        # If the form is submitted, delete the post and redirect to 'post_list'
        post.delete()
        return redirect('post_list')

    # If it's a GET request, render the confirmation page
    return render(request, 'post_delete.html', {'post': post})


def signin(request):
    if request.method == "GET":
        form = LoginForm()
        return render(request, "login.html", {"form": form})
    elif request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)
                return redirect('post_list')
        messages.error(request, "Wrong username or password")
        return render(request, "login.html", {"form": form})


@login_required
def signout(request):
    logout(request)
    return redirect('signin')


@login_required()
@permission_required('gallery.view_post', raise_exception=True)
def search(request):
    search_word = request.GET["search_word"]
    posts = Post.objects.filter(
        Q(title__icontains=search_word) | Q(content__icontains=search_word)
    )
    paginator = Paginator(posts, 10)
    page_number = request.GET.get("page")
    data = paginator.get_page(page_number)
    # Elastic search
    return render(request, "post_list.html", {"posts": data})

# @login_required
# @permission_required('gallery.view_post', raise_exception=True)
# def category_posts(request, category_id):
#     category = get_object_or_404(Category, pk=category_id)
#     posts = Post.objects.filter(category=category)
#     return render(request, 'category_posts.html', {'category': category, 'posts': posts})

templates/base_template.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
     <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

{#    <link rel="stylesheet" href="{% static 'post/css/index.css' %}">#}
</head>
<body>

{% block content %}

{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

templates/base_template2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>BLOGGERS</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:400,400i,700&display=swap">


    <style>
        body, h1, h2, h3, h4, h5, h6, p {
            font-family: 'Roboto', sans-serif;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        footer {
            margin-top: auto;
        }

        .carousel-item img {
            height: 500px;
            width: 100%;
            object-fit: cover;

        }

        .post-img {
            width: 100%;
            height: 200px;
            object-fit: cover;
        }

        .img-detail {
            width: 100%;
            height: 400px;
            object-fit: cover;
        }

        .card:hover {
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
            transform: scale(1.05);
            transition: all 0.3s ease-in-out;
        }

        .dropdown-menu {
            margin-bottom: 40px;
        }

        .bi-person {
            font-size: 1.7rem;
            color: #007bff;
            margin-right: 0.5rem;
            margin-bottom: 0;


        }

        .bi-alarm {
            padding: 0.5rem;
        }
         .category-link:hover {
        background-color: #e9ecef; /* Change this to the desired hover background color */
        color: #007bff; /* Change this to the desired hover text color */
    }
    </style>

</head>
<body>
{% include 'navbar.html' %}
{% block content %}


{% endblock %}


<footer class="bg-dark text-light py-3">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <p>&copy; 2023 Bloggers. All rights reserved.</p>
            </div>
            <div class="col-md-6 text-right">
                <a href="#" class="text-light mr-5 pr-3"><i class="bi bi-facebook"></i></a>
                <a href="#" class="text-light mr-5 pr-3"><i class="bi bi-twitter"></i></a>
                <a href="#" class="text-light mr-5 pr-3"><i class="bi bi-instagram"></i></a>
                <!-- Add other social media icons as needed -->
            </div>

        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

</body>

</html>

templates/login.html
{% extends 'base_template.html' %}
{% load crispy_forms_filters %}

{% block title %}
    Sign In
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-4">
                <form action="{% url 'signin' %}" method="post" enctype="multipart/form-data" class="shadow py-4 px-3 mt-3">
                    {% csrf_token %}
                    {{ form | crispy }}
                    <button class="btn btn-dark rounded-0 w-100">Sign In</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

templates/navbar.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'post_list' %}">Bloggers</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mynavbar">
            <form class="d-flex space-between " role="search" method="get" action="{% url 'search' %}">
                <input class="form-control me-2" name="search_word" type="search" placeholder="Search"
                       aria-label="Search">
                <button class="btn btn-outline-success " type="submit">Search</button>
            </form>
            <div>
            </div>
        </div>
        <ul class="navbar-nav ml-auto">
            <div class="dropdown" style="display: flex">
                <i class="bi bi-person"></i>
                <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                    {{ user.first_name }}
                </button>
                <ul class="dropdown-menu">
                    <li><a class="dropdown-item text-danger" href="{% url 'signout' %}">Sign Out</a></li>

                </ul>
            </div>
        </ul>
    </div>
</nav>

templates/post.html
<div class="container mt-5">
    <div class="row">
        <div class="col-md-9">
            <div class="row">
                {% for post in posts %}
                    <div class="col-md-4 mb-5">
                        <div class="card">
                            <div class="card-body">
                                {% if post.image %}
                                    <img src="{{ post.image.url }}" alt="{{ post.title }} Image"
                                         class="img-fluid post-img">
                                {% endif %}
                                {% if post.category %}
                                    <h5 class="card-title text-info"><i
                                            class="bi bi-hash text-info"></i>{{ post.category.name }}</h5>
                                {% endif %}
                                <h5 class="card-title">{{ post.title }}</h5>
                                <p class="card-text">{{ post.content|truncatewords:50 }}...</p>
                                <p class="card-text text-success"><i class="bi bi-alarm"></i>{{ post.created_at }}...
                                </p>
                                <a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-info w-100 mt-3">Read
                                    More</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
<div class="col-md-3">
    <div id="sidebar" class="bg-light p-3">
        <h2 class="h5">Categories</h2>
        <ul id="category-list" class="list-group">
            {% for category in categories %}
                <li class="list-group-item{% if category == selected_category %} active{% endif %}">
                    <a href="{% url 'post_list_filtered' category=category.name %}" class="text-decoration-none text-dark category-link">
                        {{ category.name }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>



    </div>
</div>

templates/post_delete.html
{% extends 'base_template2.html' %}
{% block content %}
    <div class="container mt-4">
        <h2>Delete Blog Post</h2>
        <p>Are you sure you want to delete "{{ post.title }}"?</p>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <button type="submit" class="btn btn-danger">Yes, Delete</button>
                <a href="{% url 'post_list' %}" class="btn btn-secondary">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

templates/post_detail.html
{% extends 'base_template2.html' %}
{% block content %}

    <div class="container">
        <div class="card-body">
            {% if post.image %}
                <img src="{{ post.image.url }}" alt="{{ post.title }} Image" class="img-detail">
            {% endif %}
            {% if post.category %}
                <h5 class="card-title text-info"><i class="bi bi-hash text-info"></i>{{ post.category.name }}</h5>
            {% endif %}
            <h5 class="card-title text-center text-info">{{ post.title }}</h5>
            <p>{{ post.content }}</p>
            <div class="text-center flex">
                {% if perms.gallery.add_post %}
                    <a href="{% url 'post_new' %}" class="btn btn-info">New</a>
                {% endif %}
                {% if perms.gallery.change_post %}
                    <a href="{% url 'post_edit' pk=post.pk %}" class="btn btn-info">Update</a>
                {% endif %}
                {% if perms.gallery.delete_post %}
                    <a href="{% url 'post_delete' pk=post.pk %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </div>
        </div>

        <a href="{% url 'post_list' %}" class="btn btn-secondary w-180">Back To Home </a>
    </div>
{% endblock %}

templates/post_edit.html
{% extends 'base_template2.html' %}
{% load crispy_forms_filters %}
{% block content %}


    <div class="container mt-4">
        <h2>Blog Post</h2>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}

            <!-- You can customize the form rendering here as needed -->
            <div class="form-group">

                {{ form.title| as_crispy_field }}
            </div>

            <div class="form-group">

                {{ form.content| as_crispy_field }}
            </div>

            <label for="id_category">Category:</label>
            <select name="category" id="id_category">
                {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.name }}</option>
                {% endfor %}
            </select>

            <button type="submit" class="btn btn-primary w-25 ">Save Changes</button>
        </form>
    </div>
{% endblock %}

templates/post_list.html
{% extends "base_template2.html" %}
{% load static %}


{% block title %}
    Blog Posts
{% endblock %}

{% block content %}

    <!-- Carousel -->

    <div id="demo" class="carousel slide" data-bs-ride="carousel">

        <!-- Indicators/dots -->
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#demo" data-bs-slide-to="0" class="active"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="1"></button>
            <button type="button" data-bs-target="#demo" data-bs-slide-to="2"></button>
        </div>

        <!-- The slideshow/carousel -->
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'carousel/AI.jpg' %}" alt="Los Angeles" class="d-block w-100">
            </div>
            <div class="carousel-item">
                <img src="{% static 'carousel/BI.jpg' %}" alt="Chicago" class="d-block w-100">
            </div>
            <div class="carousel-item">
                <img src="{% static 'carousel/DP.jpg' %}" alt="New York" class="d-block w-100">
            </div>
        </div>

        <!-- Left and right controls/icons -->
        <button class="carousel-control-prev" type="button" data-bs-target="#demo" data-bs-slide="prev">
            <span class="carousel-control-prev-icon"></span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#demo" data-bs-slide="next">
            <span class="carousel-control-next-icon"></span>
        </button>
    </div>
    {% include 'post.html' %}


    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
            {% if posts.has_previous %}
                <li class="page-item">
                    <a class="page-link" href='?page={{ posts.previous_page_number }}'>Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href='' tabindex="-1" aria-disabled="True">Previous</a>
                </li>
            {% endif %}

            {% if posts.has_next %}
                <li class="page-item">
                    <a class="page-link" href='?page={{ posts.next_page_number }}'>Next</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href='' tabindex="-1" aria-disabled="True">Next</a>
                </li>
            {% endif %}
        </ul>
    </nav>




{% endblock %}

templates/post_new.html
{% extends 'base_template2.html' %}
{% load crispy_forms_filters %}
{% block content %}
<h1>New Post</h1>
<form method="post" class="post-form" enctype="multipart/form-data" class="shadow py-4 px-3 mt-3">
    {% csrf_token %}
    <div class="form-group">
        <label for="{{ form.title.id_for_label }}">Title:</label>
        {{ form.title }}
    </div>
    <div class="form-group">
        <label for="{{ form.content.id_for_label }}">Content:</label>
        {{ form.content }}
    </div>
    <div class="form-group">
        <label for="{{ form.image.id_for_label }}">Image:</label>
        {{ form.image }}
    </div>

    <label for="id_category">Category:</label>
    <select name="category" id="id_category">
        {% for category in categories %}
            <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <button type="submit" class="save btn btn-default">Save</button>
</form>
{% endblock %}